name: Build APT Repo
on:
  push:
    branches: [ main ]
    paths:
      - 'debs/**'
  workflow_dispatch:

jobs:
  repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: install dpkg‑dev
        run: sudo apt update && sudo apt install -y dpkg-dev

      - name: generate Packages for all archs
        run: |
          dpkg-scanpackages -a iphoneos-arm debs /dev/null > Packages
          dpkg-scanpackages -a iphoneos-arm64 debs /dev/null >> Packages
          dpkg-scanpackages -a iphoneos-arm64e debs /dev/null >> Packages
          dpkg-scanpackages -a iphoneos-arm64e-roothide debs /dev/null >> Packages
          gzip -k -f Packages

      - name: commit & push index files
        run: |
          git config --global user.name "github‑actions"
          git config --global user.email "actions@github.com"
          git add Packages Packages.gz
          git commit -m "auto update apt index" || true
          git push
